CREATE TABLE [dbo].[COMUNAS](
	[CODCOMUNA] [int] NOT NULL,
	[NOMBRECOMUNA] [varchar](50) NOT NULL,
	[CODCIUDAD] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODCOMUNA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
insert into COMUNAS VALUES(	0	,'	 SIN COMUNA                    	',	0	)
insert into COMUNAS VALUES(	1	,'	 CERRILLOS                     	',	54	)
insert into COMUNAS VALUES(	2	,'	 SAN RAMON                     	',	54	)
insert into COMUNAS VALUES(	3	,'	 EL BOSQUE                     	',	54	)
insert into COMUNAS VALUES(	4	,'	 P.AGUIRRE CERDA               	',	54	)
insert into COMUNAS VALUES(	5	,'	 LO ESPEJO                     	',	54	)
insert into COMUNAS VALUES(	6	,'	 ESTAC.CENTRAL                 	',	54	)
insert into COMUNAS VALUES(	7	,'	 CERRILLOS                     	',	54	)
insert into COMUNAS VALUES(	8	,'	 LO PRADO                      	',	54	)
insert into COMUNAS VALUES(	9	,'	 CERRO NAVIA                   	',	54	)
insert into COMUNAS VALUES(	11	,'	 SANTIAGO                      	',	54	)
insert into COMUNAS VALUES(	12	,'	 CONCHALI                      	',	54	)
insert into COMUNAS VALUES(	13	,'	 PROVIDENCIA                   	',	54	)
insert into COMUNAS VALUES(	14	,'	 NUNOA                         	',	54	)
insert into COMUNAS VALUES(	15	,'	 LA REINA                      	',	54	)
insert into COMUNAS VALUES(	16	,'	 LAS CONDES                    	',	54	)
insert into COMUNAS VALUES(	17	,'	 MAIPU                         	',	54	)
insert into COMUNAS VALUES(	18	,'	 QUINTA NORMAL                 	',	54	)
insert into COMUNAS VALUES(	19	,'	 RENCA                         	',	54	)
insert into COMUNAS VALUES(	20	,'	 RECOLETA                      	',	54	)
insert into COMUNAS VALUES(	21	,'	 QUILICURA                     	',	54	)
insert into COMUNAS VALUES(	22	,'	 PUDAHUEL                      	',	54	)
insert into COMUNAS VALUES(	23	,'	 LA FLORIDA                    	',	54	)
insert into COMUNAS VALUES(	24	,'	 SAN MIGUEL                    	',	54	)
insert into COMUNAS VALUES(	25	,'	 LA GRANJA                     	',	54	)
insert into COMUNAS VALUES(	26	,'	 LA CISTERNA                   	',	54	)
insert into COMUNAS VALUES(	27	,'	 INDEPENDENCIA                 	',	54	)
insert into COMUNAS VALUES(	28	,'	 HUECHURABA                    	',	54	)
insert into COMUNAS VALUES(	29	,'	 VITACURA                      	',	54	)
insert into COMUNAS VALUES(	30	,'	 LO BARNECHEA                  	',	54	)
insert into COMUNAS VALUES(	31	,'	 LO VALLEDOR                   	',	54	)
insert into COMUNAS VALUES(	32	,'	 CHAMPA                        	',	54	)
insert into COMUNAS VALUES(	34	,'	 MACUL                         	',	54	)
insert into COMUNAS VALUES(	35	,'	 PENALOLEN                     	',	54	)
insert into COMUNAS VALUES(	36	,'	 SAN JOAQUIN                   	',	54	)
insert into COMUNAS VALUES(	37	,'	 POLPAICO                      	',	51	)
insert into COMUNAS VALUES(	41	,'	 PUENTE ALTO                   	',	52	)
insert into COMUNAS VALUES(	42	,'	 PIRQUE                        	',	52	)
insert into COMUNAS VALUES(	43	,'	 SAN J.DE MAIPO                	',	52	)
insert into COMUNAS VALUES(	52	,'	 BUIN                          	',	42	)
insert into COMUNAS VALUES(	53	,'	 PAINE                         	',	49	)
insert into COMUNAS VALUES(	54	,'	 CALERA DE TANGO               	',	53	)
insert into COMUNAS VALUES(	55	,'	 SAN BERNARDO                  	',	53	)
insert into COMUNAS VALUES(	62	,'	 PENAFLOR                      	',	50	)
insert into COMUNAS VALUES(	63	,'	 EL MONTE                      	',	45	)
insert into COMUNAS VALUES(	64	,'	 ISLA DE MAIPO                 	',	55	)
insert into COMUNAS VALUES(	65	,'	 TALAGANTE                     	',	55	)
insert into COMUNAS VALUES(	66	,'	 ALHUE                         	',	47	)
insert into COMUNAS VALUES(	67	,'	 MALLARAUCO                    	',	47	)
insert into COMUNAS VALUES(	70	,'	 ANTUCO                        	',	0	)
insert into COMUNAS VALUES(	71	,'	 MELIPILLA                     	',	47	)
insert into COMUNAS VALUES(	72	,'	 MARIA PINTO                   	',	47	)
insert into COMUNAS VALUES(	73	,'	 SAN PEDRO                     	',	47	)
insert into COMUNAS VALUES(	74	,'	 CURACAVI                      	',	44	)
insert into COMUNAS VALUES(	77	,'	 ALTO JAHUEL                   	',	42	)
insert into COMUNAS VALUES(	79	,'	 MALLOCO                       	',	46	)
insert into COMUNAS VALUES(	85	,'	 BATUCO                        	',	41	)
insert into COMUNAS VALUES(	86	,'	 PADRE HURTADO                 	',	48	)
insert into COMUNAS VALUES(	87	,'	 LAMPA                         	',	43	)
insert into COMUNAS VALUES(	88	,'	 TILTIL                        	',	43	)
insert into COMUNAS VALUES(	89	,'	 COLINA                        	',	43	)
insert into COMUNAS VALUES(	110	,'	 LA LISERA                     	',	1	)
insert into COMUNAS VALUES(	111	,'	 ARICA                         	',	1	)
insert into COMUNAS VALUES(	112	,'	 GENERAL LAGOS                 	',	1	)
insert into COMUNAS VALUES(	113	,'	 PUTRE                         	',	1	)
insert into COMUNAS VALUES(	114	,'	 BELEN                         	',	1	)
insert into COMUNAS VALUES(	115	,'	 CHOAPA                        	',	1	)
insert into COMUNAS VALUES(	116	,'	 CAMARONES                     	',	1	)
insert into COMUNAS VALUES(	117	,'	 COLCHANE                      	',	1	)
insert into COMUNAS VALUES(	118	,'	 PARINACOTA                    	',	1	)
insert into COMUNAS VALUES(	131	,'	 IQUIQUE                       	',	2	)
insert into COMUNAS VALUES(	132	,'	 POZO ALMONTE                  	',	2	)
insert into COMUNAS VALUES(	133	,'	 PICA                          	',	2	)
insert into COMUNAS VALUES(	134	,'	 LAGUNAS                       	',	2	)
insert into COMUNAS VALUES(	135	,'	 HUARA                         	',	2	)
insert into COMUNAS VALUES(	136	,'	 PISAGUA                       	',	2	)
insert into COMUNAS VALUES(	137	,'	 CHIAPA                        	',	2	)
insert into COMUNAS VALUES(	138	,'	 CAMINA                        	',	2	)
insert into COMUNAS VALUES(	139	,'	 LOS CONDORES                  	',	2	)
insert into COMUNAS VALUES(	210	,'	 BAQUEDANO                     	',	3	)
insert into COMUNAS VALUES(	211	,'	 TOCOPILLA                     	',	3	)
insert into COMUNAS VALUES(	212	,'	 TOCO                          	',	3	)
insert into COMUNAS VALUES(	231	,'	 ANTOFAGASTA                   	',	3	)
insert into COMUNAS VALUES(	232	,'	 AGUAS BLANCAS                 	',	3	)
insert into COMUNAS VALUES(	233	,'	 MEJILLONES                    	',	3	)
insert into COMUNAS VALUES(	234	,'	 SIERRA GORDA                  	',	3	)
insert into COMUNAS VALUES(	235	,'	 TALTAL                        	',	3	)
insert into COMUNAS VALUES(	236	,'	 CATALINA                      	',	3	)
insert into COMUNAS VALUES(	237	,'	 MARIA ELENA                   	',	3	)
insert into COMUNAS VALUES(	238	,'	 S.P.DE ATACAMA                	',	4	)
insert into COMUNAS VALUES(	239	,'	 OLLAGUE                       	',	4	)
insert into COMUNAS VALUES(	261	,'	 CALAMA                        	',	4	)
insert into COMUNAS VALUES(	311	,'	 CHANARAL                      	',	5	)
insert into COMUNAS VALUES(	312	,'	 D. DE ALMAGRO                 	',	5	)
insert into COMUNAS VALUES(	331	,'	 COPIAPO                       	',	6	)
insert into COMUNAS VALUES(	332	,'	 CALDERA                       	',	6	)
insert into COMUNAS VALUES(	333	,'	 TIERRA AMARILLA               	',	6	)
insert into COMUNAS VALUES(	361	,'	 VALLENAR                      	',	7	)
insert into COMUNAS VALUES(	362	,'	 FREIRINA                      	',	7	)
insert into COMUNAS VALUES(	363	,'	 HUASCO                        	',	7	)
insert into COMUNAS VALUES(	364	,'	 ALTO DEL CARMEN               	',	7	)
insert into COMUNAS VALUES(	404	,'	 COQUIMBO                      	',	8	)
insert into COMUNAS VALUES(	405	,'	 ANDACOLLO                     	',	8	)
insert into COMUNAS VALUES(	406	,'	 LA HERRADURA                  	',	8	)
insert into COMUNAS VALUES(	407	,'	 TONGOY                        	',	8	)
insert into COMUNAS VALUES(	410	,'	 LA CANTERA                    	',	8	)
insert into COMUNAS VALUES(	411	,'	 LA SERENA                     	',	9	)
insert into COMUNAS VALUES(	412	,'	 LA HIGUERA                    	',	9	)
insert into COMUNAS VALUES(	413	,'	 VICUNA                        	',	9	)
insert into COMUNAS VALUES(	414	,'	 PAIHUANO                      	',	9	)
insert into COMUNAS VALUES(	431	,'	 OVALLE                        	',	11	)
insert into COMUNAS VALUES(	432	,'	 SAMO ALTO                     	',	11	)
insert into COMUNAS VALUES(	433	,'	 MONTE PATRIA                  	',	11	)
insert into COMUNAS VALUES(	434	,'	 PUNITAQUI                     	',	11	)
insert into COMUNAS VALUES(	435	,'	 COMBARBALA                    	',	11	)
insert into COMUNAS VALUES(	436	,'	 RIO HURTADO                   	',	11	)
insert into COMUNAS VALUES(	461	,'	 ILLAPEL                       	',	10	)
insert into COMUNAS VALUES(	462	,'	 SALAMANCA                     	',	10	)
insert into COMUNAS VALUES(	463	,'	 LOS VILOS                     	',	10	)
insert into COMUNAS VALUES(	464	,'	 MINCHAS                       	',	10	)
insert into COMUNAS VALUES(	501	,'	 VINA DEL MAR                  	',	18	)
insert into COMUNAS VALUES(	502	,'	 PUCHUNCAVI                    	',	18	)
insert into COMUNAS VALUES(	503	,'	 QUINTERO                      	',	18	)
insert into COMUNAS VALUES(	504	,'	 RECREO                        	',	18	)
insert into COMUNAS VALUES(	505	,'	 CON CON                       	',	18	)
insert into COMUNAS VALUES(	506	,'	 RENACA                        	',	18	)
insert into COMUNAS VALUES(	507	,'	 PLAYA ANCHA                   	',	17	)
insert into COMUNAS VALUES(	508	,'	 SAN ROQUE                     	',	17	)
insert into COMUNAS VALUES(	509	,'	 SAN ROQUE ALTO                	',	17	)
insert into COMUNAS VALUES(	510	,'	 RODELILLO                     	',	17	)
insert into COMUNAS VALUES(	511	,'	 VALPARAISO                    	',	17	)
insert into COMUNAS VALUES(	512	,'	 LAGUNA VERDE                  	',	17	)
insert into COMUNAS VALUES(	513	,'	 VILLA ALEMANA                 	',	17	)
insert into COMUNAS VALUES(	514	,'	 QUILPUE                       	',	17	)
insert into COMUNAS VALUES(	515	,'	 CASABLANCA                    	',	17	)
insert into COMUNAS VALUES(	518	,'	 JUAN FERNANDEZ                	',	17	)
insert into COMUNAS VALUES(	519	,'	 HORCON                        	',	17	)
insert into COMUNAS VALUES(	520	,'	 LIMACHE                       	',	17	)
insert into COMUNAS VALUES(	521	,'	 OLMUE                         	',	17	)
insert into COMUNAS VALUES(	522	,'	 SANTO DOMINGO                 	',	15	)
insert into COMUNAS VALUES(	523	,'	 CARTAGENA                     	',	15	)
insert into COMUNAS VALUES(	524	,'	 EL TABO                       	',	15	)
insert into COMUNAS VALUES(	525	,'	 EL QUISCO                     	',	15	)
insert into COMUNAS VALUES(	526	,'	 ALGARROBO                     	',	15	)
insert into COMUNAS VALUES(	527	,'	 LAS CRUCES                    	',	15	)
insert into COMUNAS VALUES(	528	,'	 SAN ANTONIO                   	',	15	)
insert into COMUNAS VALUES(	541	,'	 QUILLOTA                      	',	13	)
insert into COMUNAS VALUES(	542	,'	 NOGALES                       	',	13	)
insert into COMUNAS VALUES(	543	,'	 HIJUELAS                      	',	13	)
insert into COMUNAS VALUES(	544	,'	 CALERA                        	',	13	)
insert into COMUNAS VALUES(	545	,'	 LA CRUZ                       	',	13	)
insert into COMUNAS VALUES(	551	,'	 LA LIGUA                      	',	13	)
insert into COMUNAS VALUES(	552	,'	 PETORCA                       	',	13	)
insert into COMUNAS VALUES(	553	,'	 CABILDO                       	',	13	)
insert into COMUNAS VALUES(	554	,'	 ZAPALLAR                      	',	13	)
insert into COMUNAS VALUES(	555	,'	 PAPUDO                        	',	13	)
insert into COMUNAS VALUES(	561	,'	 SAN FELIPE                    	',	16	)
insert into COMUNAS VALUES(	562	,'	 PANQUEHUE                     	',	16	)
insert into COMUNAS VALUES(	563	,'	 CATEMU                        	',	16	)
insert into COMUNAS VALUES(	564	,'	 PUTAENDO                      	',	16	)
insert into COMUNAS VALUES(	565	,'	 SANTA MARIA                   	',	16	)
insert into COMUNAS VALUES(	566	,'	 LLAY LLAY                     	',	16	)
insert into COMUNAS VALUES(	571	,'	 LOS ANDES                     	',	14	)
insert into COMUNAS VALUES(	572	,'	 CALLE LARGA                   	',	14	)
insert into COMUNAS VALUES(	573	,'	 SAN ESTEBAN                   	',	14	)
insert into COMUNAS VALUES(	574	,'	 RINCONADA                     	',	14	)
insert into COMUNAS VALUES(	581	,'	 ISLA DE PASCUA                	',	12	)
insert into COMUNAS VALUES(	609	,'	 PELEQUEN                      	',	22	)
insert into COMUNAS VALUES(	610	,'	 LO MIRANDA                    	',	22	)
insert into COMUNAS VALUES(	611	,'	 RANCAGUA                      	',	22	)
insert into COMUNAS VALUES(	612	,'	 MACHALI                       	',	22	)
insert into COMUNAS VALUES(	613	,'	 GRANEROS                      	',	22	)
insert into COMUNAS VALUES(	614	,'	 MOSTAZAL                      	',	22	)
insert into COMUNAS VALUES(	615	,'	 DONIHUE                       	',	22	)
insert into COMUNAS VALUES(	616	,'	 COLTAUCO                      	',	22	)
insert into COMUNAS VALUES(	617	,'	 CODEGUA                       	',	22	)
insert into COMUNAS VALUES(	618	,'	 PEUMO                         	',	22	)
insert into COMUNAS VALUES(	619	,'	 LAS CABRAS                    	',	22	)
insert into COMUNAS VALUES(	621	,'	 SAN VICENTE                   	',	22	)
insert into COMUNAS VALUES(	622	,'	 PICHIDEGUA                    	',	22	)
insert into COMUNAS VALUES(	623	,'	 RENGO                         	',	22	)
insert into COMUNAS VALUES(	624	,'	 REQUINOA                      	',	22	)
insert into COMUNAS VALUES(	625	,'	 OLIVAR                        	',	22	)
insert into COMUNAS VALUES(	626	,'	 MALLOA                        	',	22	)
insert into COMUNAS VALUES(	627	,'	 COINCO                        	',	22	)
insert into COMUNAS VALUES(	628	,'	 QTA.DE TILCOCO                	',	22	)
insert into COMUNAS VALUES(	632	,'	 CHUCHUNCO                     	',	22	)
insert into COMUNAS VALUES(	641	,'	 SAN FERNANDO                  	',	23	)
insert into COMUNAS VALUES(	642	,'	 CHIMBARONGO                   	',	23	)
insert into COMUNAS VALUES(	643	,'	 NANCAGUA                      	',	23	)
insert into COMUNAS VALUES(	644	,'	 PLACILLA                      	',	23	)
insert into COMUNAS VALUES(	645	,'	 SANTA CRUZ                    	',	23	)
insert into COMUNAS VALUES(	646	,'	 LOLOL                         	',	23	)
insert into COMUNAS VALUES(	647	,'	 PALMILLA                      	',	23	)
insert into COMUNAS VALUES(	648	,'	 PERALILLO                     	',	23	)
insert into COMUNAS VALUES(	649	,'	 CHEPICA                       	',	23	)
insert into COMUNAS VALUES(	651	,'	 PAREDONES                     	',	23	)
insert into COMUNAS VALUES(	652	,'	 MARCHIGUE                     	',	23	)
insert into COMUNAS VALUES(	653	,'	 LITUECHE                      	',	23	)
insert into COMUNAS VALUES(	654	,'	 PICHILEMU                     	',	23	)
insert into COMUNAS VALUES(	655	,'	 PUMANQUE                      	',	23	)
insert into COMUNAS VALUES(	656	,'	 LA ESTRELLA                   	',	23	)
insert into COMUNAS VALUES(	657	,'	 NAVIDAD                       	',	23	)
insert into COMUNAS VALUES(	658	,'	 ROSARIO                       	',	23	)
insert into COMUNAS VALUES(	659	,'	 BUCALEMU                      	',	23	)
insert into COMUNAS VALUES(	660	,'	 HOSPITAL                      	',	19	)
insert into COMUNAS VALUES(	661	,'	 LINDEROS                      	',	21	)
insert into COMUNAS VALUES(	662	,'	 HUELQUEN                      	',	20	)
insert into COMUNAS VALUES(	710	,'	 LONTUE                        	',	25	)
insert into COMUNAS VALUES(	711	,'	 CURICO                        	',	25	)
insert into COMUNAS VALUES(	712	,'	 ROMERAL                       	',	25	)
insert into COMUNAS VALUES(	713	,'	 TENO                          	',	25	)
insert into COMUNAS VALUES(	714	,'	 RAUCO                         	',	25	)
insert into COMUNAS VALUES(	715	,'	 LICANTEN                      	',	25	)
insert into COMUNAS VALUES(	716	,'	 VICHUQUEN                     	',	25	)
insert into COMUNAS VALUES(	717	,'	 HUALANE                       	',	25	)
insert into COMUNAS VALUES(	718	,'	 MOLINA                        	',	25	)
insert into COMUNAS VALUES(	719	,'	 SAGRADA FAMILIA               	',	25	)
insert into COMUNAS VALUES(	730	,'	 CUMPEO                        	',	28	)
insert into COMUNAS VALUES(	731	,'	 TALCA                         	',	28	)
insert into COMUNAS VALUES(	732	,'	 SAN CLEMENTE                  	',	28	)
insert into COMUNAS VALUES(	733	,'	 PELARCO                       	',	28	)
insert into COMUNAS VALUES(	734	,'	 RIO CLARO                     	',	28	)
insert into COMUNAS VALUES(	735	,'	 PENCAHUE                      	',	28	)
insert into COMUNAS VALUES(	736	,'	 MAULE                         	',	28	)
insert into COMUNAS VALUES(	737	,'	 CUREPTO                       	',	28	)
insert into COMUNAS VALUES(	738	,'	 CONSTITUCION                  	',	28	)
insert into COMUNAS VALUES(	739	,'	 EMPEDRADO                     	',	28	)
insert into COMUNAS VALUES(	741	,'	 SAN JAVIER                    	',	28	)
insert into COMUNAS VALUES(	759	,'	 VILLA ALEGRE                  	',	26	)
insert into COMUNAS VALUES(	760	,'	 PENUELAS                      	',	26	)
insert into COMUNAS VALUES(	761	,'	 LINARES                       	',	26	)
insert into COMUNAS VALUES(	762	,'	 YERBAS BUENAS                 	',	26	)
insert into COMUNAS VALUES(	763	,'	 COLBUN                        	',	26	)
insert into COMUNAS VALUES(	764	,'	 LONGAVI                       	',	26	)
insert into COMUNAS VALUES(	765	,'	 PARRAL                        	',	27	)
insert into COMUNAS VALUES(	766	,'	 RETIRO                        	',	26	)
insert into COMUNAS VALUES(	767	,'	 CHANCO                        	',	24	)
insert into COMUNAS VALUES(	768	,'	 CAUQUENES                     	',	24	)
insert into COMUNAS VALUES(	770	,'	 PELLUHUE                      	',	24	)
insert into COMUNAS VALUES(	801	,'	 TALCAHUANO                    	',	32	)
insert into COMUNAS VALUES(	802	,'	 HUALPENCILLO                  	',	32	)
insert into COMUNAS VALUES(	811	,'	 CHILLAN                       	',	29	)
insert into COMUNAS VALUES(	812	,'	 PINTO                         	',	29	)
insert into COMUNAS VALUES(	813	,'	 COIHUECO                      	',	29	)
insert into COMUNAS VALUES(	814	,'	 QUIRIHUE                      	',	29	)
insert into COMUNAS VALUES(	815	,'	 NINHUE                        	',	29	)
insert into COMUNAS VALUES(	816	,'	 PORTEZUELO                    	',	29	)
insert into COMUNAS VALUES(	817	,'	 COBQUECURA                    	',	29	)
insert into COMUNAS VALUES(	818	,'	 TREGUACO                      	',	29	)
insert into COMUNAS VALUES(	819	,'	 SAN CARLOS                    	',	29	)
insert into COMUNAS VALUES(	821	,'	 NIQUEN                        	',	29	)
insert into COMUNAS VALUES(	822	,'	 SAN FABIAN                    	',	29	)
insert into COMUNAS VALUES(	823	,'	 SAN NICOLAS                   	',	29	)
insert into COMUNAS VALUES(	824	,'	 BULNES                        	',	29	)
insert into COMUNAS VALUES(	825	,'	 SAN IGNACIO                   	',	29	)
insert into COMUNAS VALUES(	826	,'	 QUILLON                       	',	29	)
insert into COMUNAS VALUES(	827	,'	 YUNGAY                        	',	29	)
insert into COMUNAS VALUES(	828	,'	 PEMUCO                        	',	29	)
insert into COMUNAS VALUES(	829	,'	 EL CARMEN                     	',	29	)
insert into COMUNAS VALUES(	831	,'	 RANQUIL                       	',	29	)
insert into COMUNAS VALUES(	832	,'	 COELEMU                       	',	29	)
insert into COMUNAS VALUES(	833	,'	 HUAPE                         	',	29	)
insert into COMUNAS VALUES(	835	,'	 LIRQUEN                       	',	30	)
insert into COMUNAS VALUES(	836	,'	 COPIULEMO                     	',	30	)
insert into COMUNAS VALUES(	837	,'	 CARAMPANGUE                   	',	30	)
insert into COMUNAS VALUES(	838	,'	 DICHATO                       	',	30	)
insert into COMUNAS VALUES(	839	,'	 CORONEL                       	',	30	)
insert into COMUNAS VALUES(	840	,'	 LOTA                          	',	30	)
insert into COMUNAS VALUES(	841	,'	 SANTA JUANA                   	',	30	)
insert into COMUNAS VALUES(	842	,'	 LEBU                          	',	30	)
insert into COMUNAS VALUES(	843	,'	 LOS ALAMOS                    	',	30	)
insert into COMUNAS VALUES(	844	,'	 ARAUCO                        	',	30	)
insert into COMUNAS VALUES(	845	,'	 CURANILAHUE                   	',	30	)
insert into COMUNAS VALUES(	846	,'	 CANETE                        	',	30	)
insert into COMUNAS VALUES(	847	,'	 CONTULMO                      	',	30	)
insert into COMUNAS VALUES(	848	,'	 TIRUA                         	',	30	)
insert into COMUNAS VALUES(	849	,'	 CHIGUAYANTE                   	',	30	)
insert into COMUNAS VALUES(	851	,'	 CONCEPCION                    	',	30	)
insert into COMUNAS VALUES(	852	,'	 PENCO                         	',	30	)
insert into COMUNAS VALUES(	853	,'	 HUALQUI                       	',	30	)
insert into COMUNAS VALUES(	854	,'	 FLORIDA                       	',	30	)
insert into COMUNAS VALUES(	855	,'	 TOME                          	',	30	)
insert into COMUNAS VALUES(	862	,'	 MONTE AGUILA                  	',	31	)
insert into COMUNAS VALUES(	863	,'	 HUEPIL                        	',	31	)
insert into COMUNAS VALUES(	864	,'	 MININCO                       	',	31	)
insert into COMUNAS VALUES(	865	,'	 SANTA FE                      	',	31	)
insert into COMUNAS VALUES(	866	,'	 RENAICO                       	',	31	)
insert into COMUNAS VALUES(	867	,'	 ANGOL                         	',	31	)
insert into COMUNAS VALUES(	868	,'	 PUREN                         	',	31	)
insert into COMUNAS VALUES(	869	,'	 LOS SAUCES                    	',	31	)
insert into COMUNAS VALUES(	871	,'	 LOS ANGELES                   	',	31	)
insert into COMUNAS VALUES(	872	,'	 SANTA BARBARA                 	',	31	)
insert into COMUNAS VALUES(	873	,'	 LAJA                          	',	31	)
insert into COMUNAS VALUES(	874	,'	 QUILLECO                      	',	31	)
insert into COMUNAS VALUES(	875	,'	 NACIMIENTO                    	',	31	)
insert into COMUNAS VALUES(	876	,'	 NEGRETE                       	',	31	)
insert into COMUNAS VALUES(	877	,'	 MULCHEN                       	',	31	)
insert into COMUNAS VALUES(	878	,'	 QUILACO                       	',	31	)
insert into COMUNAS VALUES(	879	,'	 YUMBEL                        	',	31	)
insert into COMUNAS VALUES(	881	,'	 CABRERO                       	',	31	)
insert into COMUNAS VALUES(	882	,'	 SAN ROSENDO                   	',	31	)
insert into COMUNAS VALUES(	883	,'	 TUCAPEL                       	',	31	)
insert into COMUNAS VALUES(	884	,'	 ANTUCO                        	',	31	)
insert into COMUNAS VALUES(	914	,'	 CHERQUENCO                    	',	33	)
insert into COMUNAS VALUES(	915	,'	 COLLIPULLI                    	',	33	)
insert into COMUNAS VALUES(	916	,'	 ERCILLA                       	',	33	)
insert into COMUNAS VALUES(	917	,'	 TRAIGUEN                      	',	33	)
insert into COMUNAS VALUES(	918	,'	 LUMACO                        	',	33	)
insert into COMUNAS VALUES(	919	,'	 VICTORIA                      	',	33	)
insert into COMUNAS VALUES(	920	,'	 MELIPEUCO                     	',	33	)
insert into COMUNAS VALUES(	921	,'	 CURACAUTIN                    	',	33	)
insert into COMUNAS VALUES(	922	,'	 LONQUIMAY                     	',	33	)
insert into COMUNAS VALUES(	923	,'	 CURARREHUE                    	',	33	)
insert into COMUNAS VALUES(	931	,'	 TEMUCO                        	',	33	)
insert into COMUNAS VALUES(	932	,'	 VILCUN                        	',	33	)
insert into COMUNAS VALUES(	933	,'	 FREIRE                        	',	33	)
insert into COMUNAS VALUES(	934	,'	 CUNCO                         	',	33	)
insert into COMUNAS VALUES(	935	,'	 LONCOCHE                      	',	33	)
insert into COMUNAS VALUES(	936	,'	 VILLARRICA                    	',	33	)
insert into COMUNAS VALUES(	937	,'	 PUCON                         	',	33	)
insert into COMUNAS VALUES(	938	,'	 PITRUFQUEN                    	',	33	)
insert into COMUNAS VALUES(	939	,'	 GORBEA                        	',	33	)
insert into COMUNAS VALUES(	941	,'	 TOLTEN                        	',	33	)
insert into COMUNAS VALUES(	942	,'	 NUEVA IMPERIAL                	',	33	)
insert into COMUNAS VALUES(	943	,'	 CARAHUE                       	',	33	)
insert into COMUNAS VALUES(	944	,'	 SAAVEDRA                      	',	33	)
insert into COMUNAS VALUES(	945	,'	 LAUTARO                       	',	33	)
insert into COMUNAS VALUES(	946	,'	 PERQUENCO                     	',	33	)
insert into COMUNAS VALUES(	947	,'	 GALVARINO                     	',	33	)
insert into COMUNAS VALUES(	948	,'	 TEODORO SCHMIDT               	',	33	)
insert into COMUNAS VALUES(	949	,'	 LASTARRIA                     	',	33	)
insert into COMUNAS VALUES(	950	,'	 QUINO                         	',	33	)
insert into COMUNAS VALUES(	951	,'	 CHOL CHOL                     	',	33	)
insert into COMUNAS VALUES(	952	,'	 PADRE LAS CASAS               	',	33	)
insert into COMUNAS VALUES(	953	,'	 QUEPE                         	',	33	)
insert into COMUNAS VALUES(	955	,'	 LICAN RAY                     	',	33	)
insert into COMUNAS VALUES(	1001	,'	 LIQUINE                       	',	38	)
insert into COMUNAS VALUES(	1002	,'	 NELTUME                       	',	38	)
insert into COMUNAS VALUES(	1003	,'	 LLIFEN                        	',	38	)
insert into COMUNAS VALUES(	1004	,'	 MALALHUE                      	',	38	)
insert into COMUNAS VALUES(	1005	,'	 REUMEN                        	',	38	)
insert into COMUNAS VALUES(	1006	,'	 ANTILHUE                      	',	38	)
insert into COMUNAS VALUES(	1007	,'	 PISHUINCO                     	',	38	)
insert into COMUNAS VALUES(	1008	,'	 PICHIRROPULLI                 	',	38	)
insert into COMUNAS VALUES(	1009	,'	 MEHUIN                        	',	38	)
insert into COMUNAS VALUES(	1010	,'	 HUELLELHUE                    	',	38	)
insert into COMUNAS VALUES(	1011	,'	 VALDIVIA                      	',	38	)
insert into COMUNAS VALUES(	1012	,'	 MARIQUINA                     	',	38	)
insert into COMUNAS VALUES(	1013	,'	 LANCO                         	',	38	)
insert into COMUNAS VALUES(	1014	,'	 LOS LAGOS                     	',	38	)
insert into COMUNAS VALUES(	1015	,'	 FUTRONO                       	',	38	)
insert into COMUNAS VALUES(	1016	,'	 CORRAL                        	',	38	)
insert into COMUNAS VALUES(	1017	,'	 MAFIL                         	',	38	)
insert into COMUNAS VALUES(	1018	,'	 PANGUIPULLI                   	',	38	)
insert into COMUNAS VALUES(	1019	,'	 LA UNION                      	',	38	)
insert into COMUNAS VALUES(	1020	,'	 HUALAIHUE                     	',	38	)
insert into COMUNAS VALUES(	1021	,'	 PAILLACO                      	',	38	)
insert into COMUNAS VALUES(	1022	,'	 RIO BUENO                     	',	38	)
insert into COMUNAS VALUES(	1023	,'	 LAGO RANCO                    	',	38	)
insert into COMUNAS VALUES(	1024	,'	 CONARIPE                      	',	38	)
insert into COMUNAS VALUES(	1025	,'	 HUICHAHUE                     	',	38	)
insert into COMUNAS VALUES(	1026	,'	 RIACHUELO                     	',	35	)
insert into COMUNAS VALUES(	1027	,'	 S.J.DE LA COSTA               	',	35	)
insert into COMUNAS VALUES(	1028	,'	 RUPANCO                       	',	35	)
insert into COMUNAS VALUES(	1029	,'	 PAILLAGUE                     	',	35	)
insert into COMUNAS VALUES(	1031	,'	 OSORNO                        	',	35	)
insert into COMUNAS VALUES(	1032	,'	 SAN PABLO                     	',	35	)
insert into COMUNAS VALUES(	1033	,'	 PUERTO OCTAY                  	',	35	)
insert into COMUNAS VALUES(	1034	,'	 ENTRE LAGOS                   	',	35	)
insert into COMUNAS VALUES(	1035	,'	 RIO NEGRO                     	',	35	)
insert into COMUNAS VALUES(	1036	,'	 PURRANQUE                     	',	35	)
insert into COMUNAS VALUES(	1037	,'	 PUYUHUAPI                     	',	36	)
insert into COMUNAS VALUES(	1041	,'	 PUERTO MONTT                  	',	36	)
insert into COMUNAS VALUES(	1042	,'	 COCHAMO                       	',	36	)
insert into COMUNAS VALUES(	1043	,'	 CALBUCO                       	',	36	)
insert into COMUNAS VALUES(	1044	,'	 MAULLIN                       	',	36	)
insert into COMUNAS VALUES(	1045	,'	 LOS MUERMOS                   	',	36	)
insert into COMUNAS VALUES(	1046	,'	 PUERTO VARAS                  	',	37	)
insert into COMUNAS VALUES(	1047	,'	 FRESIA                        	',	36	)
insert into COMUNAS VALUES(	1048	,'	 FRUTILLAR                     	',	36	)
insert into COMUNAS VALUES(	1049	,'	 LLANQUIHUE                    	',	36	)
insert into COMUNAS VALUES(	1061	,'	 CASTRO                        	',	34	)
insert into COMUNAS VALUES(	1062	,'	 CHONCHI                       	',	36	)
insert into COMUNAS VALUES(	1063	,'	 QUEILEN                       	',	36	)
insert into COMUNAS VALUES(	1064	,'	 QUELLON                       	',	36	)
insert into COMUNAS VALUES(	1065	,'	 PUQUELDON                     	',	36	)
insert into COMUNAS VALUES(	1066	,'	 ANCUD                         	',	36	)
insert into COMUNAS VALUES(	1067	,'	 QUEMCHI                       	',	36	)
insert into COMUNAS VALUES(	1068	,'	 DALCAHUE                      	',	36	)
insert into COMUNAS VALUES(	1069	,'	 ACHAO                         	',	36	)
insert into COMUNAS VALUES(	1070	,'	 QUINCHAO                      	',	36	)
insert into COMUNAS VALUES(	1071	,'	 CURACO DE VELEZ               	',	36	)
insert into COMUNAS VALUES(	1072	,'	 CHAITEN                       	',	36	)
insert into COMUNAS VALUES(	1073	,'	 FUTALEUFU                     	',	36	)
insert into COMUNAS VALUES(	1074	,'	 PALENA                        	',	36	)
insert into COMUNAS VALUES(	1110	,'	 BALMACEDA                     	',	39	)
insert into COMUNAS VALUES(	1111	,'	 AYSEN                         	',	39	)
insert into COMUNAS VALUES(	1112	,'	 CISNES                        	',	39	)
insert into COMUNAS VALUES(	1113	,'	 COYHAIQUE                     	',	39	)
insert into COMUNAS VALUES(	1114	,'	 CORCOVADO                     	',	39	)
insert into COMUNAS VALUES(	1121	,'	 CHILE CHICO                   	',	39	)
insert into COMUNAS VALUES(	1122	,'	 GUADAL                        	',	39	)
insert into COMUNAS VALUES(	1123	,'	 RIO IBANEZ                    	',	39	)
insert into COMUNAS VALUES(	1124	,'	 GUAITECAS                     	',	39	)
insert into COMUNAS VALUES(	1131	,'	 COCHRANE                      	',	39	)
insert into COMUNAS VALUES(	1132	,'	 OHIGGINS                      	',	39	)
insert into COMUNAS VALUES(	1133	,'	 TORTEL                        	',	39	)
insert into COMUNAS VALUES(	1134	,'	 LAGO VERDE                    	',	39	)
insert into COMUNAS VALUES(	1210	,'	 PUERTO WILLIAMS               	',	40	)
insert into COMUNAS VALUES(	1211	,'	 NATALES                       	',	40	)
insert into COMUNAS VALUES(	1212	,'	 CERRO CASTILLO                	',	40	)
insert into COMUNAS VALUES(	1221	,'	 MAGALLANES                    	',	40	)
insert into COMUNAS VALUES(	1222	,'	 RIO VERDE                     	',	40	)
insert into COMUNAS VALUES(	1223	,'	 MORRO CHICO                   	',	40	)
insert into COMUNAS VALUES(	1224	,'	 SAN GREGORIO                  	',	40	)
insert into COMUNAS VALUES(	1225	,'	 PUNTA ARENAS                  	',	40	)
insert into COMUNAS VALUES(	1226	,'	 TIMAUKEL                      	',	40	)
insert into COMUNAS VALUES(	1227	,'	 T. DEL PAINE                  	',	40	)
insert into COMUNAS VALUES(	1231	,'	 PORVENIR                      	',	40	)
insert into COMUNAS VALUES(	1232	,'	 PRIMAVERA                     	',	40	)
insert into COMUNAS VALUES(	1233	,'	 BAHIA INUTIL                  	',	40	)
insert into COMUNAS VALUES(	1241	,'	 NAVARINO                      	',	40	)
insert into COMUNAS VALUES(	1242	,'	 ANTARTICA                     	',	40	)
insert into COMUNAS VALUES(	1243	,'	 LAGUNA BLANCA                 	',	40	)


CREATE TABLE [dbo].[CIUDAD](
	[CODCIUDAD] [tinyint] NOT NULL,
	[NOMBRECIUDAD] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODCIUDAD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

Insert into CIUDAD VALUES (1,'ARICA')
Insert into CIUDAD VALUES (54,'SANTIAGO')


