
CREATE PROCEDURE SP_ARTICULOS (@CODARTICULO		INT ,
							@NOMBREARTICULO	VARCHAR(100),
							@PRECIONETO		MONEY,
							@STOCK			INT,
							@ANULA CHAR(1))
AS 
BEGIN

	IF @ANULA = 'A'	
	BEGIN
	UPDATE ARTICULO
		SET ESTADO='A'
		WHERE CODARTICULO = @CODARTICULO
		AND STOCK	= 0
		IF @@ROWCOUNT=0
		PRINT 'NO SE ANULA ARTICULO'
		RETURN
	END
	
	
	IF EXISTS
	(SELECT 1 FROM ARTICULO
	 WHERE CODARTICULO= @CODARTICULO)
	 BEGIN
			UPDATE ARTICULO
			SET NOMBREARTICULO = @NOMBREARTICULO,
				PRECIONETO = @PRECIONETO,
				STOCK	= @STOCK
			WHERE CODARTICULO = @CODARTICULO
			PRINT 'ARTICULO CREADO'
			
			SELECT CODARTICULO,NOMBREARTICULO,
				   PRECIONETO,DBO.FN_CALIVA(PRECIONETO)PRECIOIVA,STOCK
			FROM ARTICULO
			WHERE CODARTICULO = @CODARTICULO
	 END
	 ELSE
	 BEGIN
			INSERT INTO ARTICULO 
			VALUES (@CODARTICULO,@NOMBREARTICULO,@PRECIONETO,@STOCK,'V')
			PRINT 'ARTICULO INGRESADO'
	 END

END
							
							
CREATE FUNCTION FN_CALIVA(@PRECIO MONEY)
RETURNS MONEY
AS
BEGIN
	RETURN (@PRECIO * 1.19)
END

EXEC SP_ARTICULOS 2,'SILLA',100,10,''

