create database ejemplo;

use ejemplo;

/*1.- CREAR TABLA */

CREATE TABLE CLIENTES(
	RUT CHAR(12) PRIMARY KEY,
	NOMBRE VARCHAR(60)
)


CREATE TABLE VENTAS(
	RUT CHAR(12) REFERENCES CLIENTES(RUT),
	FECHAVENTA  DATE, 
	UNIDADES INT, 
	MONTOVENTA  MONEY
	)
/*INSERTAR VALORES*/

INSERT INTO CLIENTES VALUES('1-9','JUAN PEREZ')
INSERT INTO CLIENTES VALUES('3-5','ROGELIO ROJAS')
INSERT INTO CLIENTES VALUES('2-7','PATRICIO DONALDS')
INSERT INTO CLIENTES VALUES('4-6','JESICA GALINDO')



/*INSERTAR VALORES*/

INSERT INTO Ventas VALUES('1-9',GETDATE(),2,15000)
INSERT INTO Ventas VALUES('1-9','20110102',1,5000)
INSERT INTO Ventas VALUES('1-9','20110202',10,25000)
INSERT INTO Ventas VALUES('1-9','20110302',3,5000)
INSERT INTO Ventas VALUES('3-5',GETDATE(),2,1000)
INSERT INTO Ventas VALUES('3-5','20110102',1,10000)
INSERT INTO Ventas VALUES('2-7','20110202',10,5000)

/*
1.SELECCIONAR TODOS LOS CLIENTES Y SUS VENTAS
2.SELECCIONAR TODOS LOS CLIENTES Y SUS VENTAS ORDENADOS DESDE LAS VENTAS MENOR A MAYOR
3.SELECCIONAR RUT,NOMBRE Y MONTO DE LA VENTA PARA EL CLIENTE 1-9
4.SELECCIONAR VENTA MAYOR
5.SELECCIONAR RUT, NOMBRE Y MONTO VENTA DEL CLIENTE QUE TENGA MAYOR VENTA
6.CONTAR LAS VENTAS DEL CLIENTE 3-5
7.SELECCIONAR RUT, NOMBRE Y DDEVOLVER EL NÚMERO DE VENTAS POR CLIENTES
8.SELECCIONAR RUT,NOMBRE Y LA SUMA DEL MONTO DE LA VENTA PARA EL CLIENTE 1-9
9.SELECCIONAR RUT,NOMBRE Y LA SUMA DEL MONTO DE LA VENTA PARA TODOS LOS CLIENTES ORDENADOS DE LA MAYOR VENTA
10.SELECCIONAR Y MOSTRAR EL PROMEDIO DE LAS VENTAS PARA EL CLIENTES 1-9
11.SELECCIONAR PROMEDIO DE LAS VENTAS PARA CADA UNO DE LOS CLIENTES (RUT,NOMBRE  )
12.SELECCIONAR LOS DOS PRIMEROS REGISTROS DE LA ENTIDAD CLIENTE
*/

select * from clientes
select * from ventas

select * from CLIENTES c
inner join VENTAS v
on c.RUT = v.RUT
order by v.MONTOVENTA asc

select c.RUT,c.NOMBRE,v.MONTOVENTA from CLIENTES c
inner join VENTAS v
on c.RUT = v.RUT and v.RUT = '1-9'

select c.nombre,c.rut,v.MONTOVENTA from CLIENTES c
inner join VENTAS v
on 
c.rut = v.RUT 
and
v.MONTOVENTA = (select MAX(montoventa) from VENTAS)

select COUNT(*) as cuenta from VENTAS where RUT='3-5'

select c.rut,c.nombre,COUNT(*) as cuenta
from CLIENTES c
inner join VENTAS v
	on c.RUT = v.RUT
group by c.RUT,c.NOMBRE

select c.rut,c.nombre,SUM(v.MONTOVENTA) as SUMA
from CLIENTES c
inner join VENTAS v
	on c.RUT = v.RUT
	and c.RUT = '1-9'
group by c.RUT,c.NOMBRE

select c.rut,c.nombre,SUM(v.MONTOVENTA) as SUMA
from CLIENTES c
inner join VENTAS v
	on c.RUT = v.RUT
group by c.RUT,c.NOMBRE
order by SUMA desc


select TOP 2 * from CLIENTES 


/*
PROCESO ALMACENADO
*/

CREATE TABLE CLIENTE(
	RUT CHAR(12) PRIMARY KEY,
	NOMBRES VARCHAR(50) NOT NULL,
	FECHANACIMIENTO DATE NOT NULL
)

INSERT INTO CLIENTE VALUES('1-9','JUAN PEREZ','19860201')
INSERT INTO CLIENTE VALUES('2-3','ROGELIO ROJAS','20110102')
INSERT INTO CLIENTE VALUES('5-8','PATRICIO DONALDS','20140826')

CREATE PROCEDURE sp_LeerCliente (@Rut varchar(12))
AS
begin
	SELECT RUT,NOMBRES,FECHANACIMIENTO
	FROM CLIENTE
	WHERE RUT = @Rut
end

ALTER PROCEDURE sp_LeerCliente (@Rut varchar(12))
AS
begin
	SELECT RUT,NOMBRES,FECHANACIMIENTO
	FROM CLIENTE
	WHERE RUT = @Rut
	IF @@ROWCOUNT = 0
		PRINT 'NO EXISTE CLIENTE'
end

sp_LeerCliente'1-9'
sp_LeerCliente'2-3'
sp_LeerCliente'5-8'
sp_LeerCliente'0-0' /*error*/

CREATE PROCEDURE sp_LeerClienteOutPut	@rut char(12), 
					@nombre varchar(50) output, 
					@fechanacimiento date output
as
begin
	select @nombre=nombres, 
		   @fechanacimiento = fechanacimiento
	from cliente
	where rut =  @rut
	
	/*
	print @nombre
	print @fechanacimiento	
	*/
end


sp_LeerClienteOutPut '1-9','',''

declare @nom varchar(50),
		@fechanac date
		
exec sp_LeerClienteOutPut'1-9',@nom output, @fechanac output


/*
 buscando 
*/

CREATE PROCEDURE Sp_excisteCliente @rut varchar(12)
AS
BEGIN
	DECLARE @cont AS INT
	SELECT @cont=COUNT(*) FROM CLIENTE
	WHERE rut = @rut
	IF @cont>0
	BEGIN
		PRINT 'EXISTE CLIENTE'
		RETURN
	END
	ELSE
	BEGIN
		PRINT 'NO EXISTE CLIENTE'
		RETURN
	END
END

Sp_excisteCliente'1-9';
